# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GFvT4b4bMqqfvGpKCJJRw-OJJe4uOTs2
"""

#listede yarıların yerlerini değiştirmek

mylist=[1,2,3,4,5,6,7,8]
a=(len(mylist)+1)//2
print(a)


mylist[:a],mylist[a:] = mylist[a:],mylist[:a]

print(mylist)

# kullanıcıdan alınan değere kadar olan çift sayıların bulunması
n = int(input("Please enter an integer: "))
nlist = list(range(0,n+1,2))

print(nlist)