# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mMyh9nWLMueW0AsvzFs-hyyly8og5AXU
"""

#User Login Application

username = "KeremKoker"
password = "PhytonOgren"


n= input("Please Enter Your Username :")
m= input("Please Enter Your Password: ")

if (username != n and password == m):
    print("User Name Is Not True!")
elif (username == n and password != m):
    print("Your password is not True!")
elif (username != n and password!= m):
    print("Your user name and password both are not right!")
else:
    print("Welcome in!")

userpass = {"username":"Keremci", "password":"Phytoncu"}
a = input("Please Enter Your Username:")
b = input("Please Enter Your Password:")

if (userpass['username'] != a and userpass["password"] == b):
    print("User Name Is Not True!")
elif (userpass['username'] == a and userpass["password"] != b):
    print("Your password is not True!")
elif (userpass['username'] != a and userpass["password"] != m):
    print("Your user name and password both are not right!")
else:
    print("Welcome in!")