# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K3I522rnRi-A54fuheTTYk3Vz7_wdmcq
"""

x, y, z, a, b = input("Please Enter 5 Student Names: ").split()

StudentInfo = [xM1:30, xM2:65, xF:70, yM1:89,yM2:78,yF:68,zM1:78,zM2:55,zF:100,aM1:56,aM2:78,aF:89,bM1:67,bM2:45,bF:60]

print(StudentInfo)
PassingGrades ={xPG:((StudentInfo[xM1]*0,3)+(StudentInfo[xM2]*0,3)+(StudentInfo[xF]*0,4)),
               yPG:((StudentInfo[yM1]*0,3)+(StudentInfo[yM2]*0,3)+(StudentInfo[yF]*0,4)),
               zPG:((StudentInfo[zM1]*0,3)+(StudentInfo[zM2]*0,3)+(StudentInfo[zF]*0,4)),
               aPG:((StudentInfo[aM1]*0,3)+(StudentInfo[aM2]*0,3)+(StudentInfo[aF]*0,4)),
               bPG:((StudentInfo[bM1]*0,3)+(StudentInfo[bM2]*0,3)+(StudentInfo[bF]*0,4))
               }
Glist = [PassingGrades[xPG],PassingGrades[yPG],PassingGrades[zPG],PassingGrades[aPG],PassingGrades[bPG]]
print(mylist[0])

max1 = Glist[0]

for i in mylist:
    if i > max1:
        max1 = i
        print("maxgrade: ", max1)
        print("i: ", i)

x, y, z, a, b = input("Please Enter 5 Student Names: ").split()
import numpy as np
import pandas as pd
m = np.random.randint(1,100, size = (3,5))
m1 = m
df1 = pd.DataFrame(m, index=["Mid", "Project", "Final"], columns=[x,y,z,a,b])
df1

#m2 = m1[0:0]*0.3 + m1[1:0]*0.3 + m1[2:0]*0.4
#m3 = m1[0:1]*0.3 + m1[1:1]*0.3 + m1[2:1]*0.4
#m4 = m1[0:2]*0.3 + m1[1:2]*0.3 + m1[2:2]*0.4
#m5 = m1[0:3]*0.3 + m1[1:3]*0.3 + m1[2:3]*0.4
#m6 = m1[0:4]*0.3 + m1[1:4]*0.3 + m1[2:4]*0.4

#m7 = np.array([m2,m3,m4,m5,m6])
#print(m7)

#df1 = pd.DataFrame(m, index=["Mid", "Project", "Final"], columns=[x,y,z,a,b])
#df2 = pd.Dataframe(m7, index=["PG"], columns=[x,y,z,a,b])
#df2



#a = df1[0]*0.3 + df1[1]*0.3 + df1[2]
#a